<?php
/**
 * Fixture artwork: the ground under the two clubs' badges.
 *
 * Expects $m (a match row joined to stadium and both teams) and optionally
 * $artClass to override the wrapper.
 *
 * The 2021 build had one image, evevsliv.png, printed on every card regardless
 * of who was playing. Everything here is generated by docs/generate-artwork.py
 * and resolved per fixture, with placeholder.svg behind it for anything an
 * admin creates without artwork.
 */
$artClass = $artClass ?? 'fixture-art';
?>
<div class="<?= e($artClass) ?>">
    <img class="fixture-art-bg" src="<?= e(asset_image($m['venue_photo'] ?? null)) ?>"
         alt="" width="400" height="225" loading="lazy" decoding="async">
    <div class="fixture-art-crests">
        <?php /* alt="" on the badges: the fixture title beneath already names
                 both clubs, so announcing them again is repetition. */ ?>
        <img src="<?= e(asset_image($m['home_photo'] ?? null)) ?>" alt=""
             width="64" height="64" loading="lazy" decoding="async">
        <span class="fixture-art-v" aria-hidden="true">v</span>
        <img src="<?= e(asset_image($m['away_photo'] ?? null)) ?>" alt=""
             width="64" height="64" loading="lazy" decoding="async">
    </div>
    <span class="fixture-art-date">
        <?= e(date('D j M', strtotime((string) $m['match_date']))) ?>
    </span>
</div>
